"""Free statement reader: no AI, no internet.

- PDF statements generated by the bank carry real text: each line that starts with a date
  and ends with an amount is a transaction.
- CSV and OFX exports are read column by column.

Returns the same shape as extractor.extract(), so the review screen works the same way.
"""

import csv
import io
import re
from datetime import date, timedelta

from pypdf import PdfReader

from . import documents
from .categorizer import clean_merchant, guess_category
from .extractor import ExtractionError

MONTHS = {"jan": 1, "fev": 2, "feb": 2, "mar": 3, "abr": 4, "apr": 4, "mai": 5, "may": 5, "jun": 6, "jul": 7,
          "ago": 8, "aug": 8, "set": 9, "sep": 9, "out": 10, "oct": 10, "nov": 11, "dez": 12, "dec": 12}
_MONTH_NAMES = "|".join(MONTHS)


INSTALLMENT = re.compile(r"(?:parc(?:ela)?\.?\s*)?\b(\d{1,2})\s*(?:/|de)\s*(\d{1,2})\b(?!.*\b\d{1,2}\s*(?:/|de)\s*\d{1,2}\b)", re.IGNORECASE)
# "•••• 1234", "**** 1234", "XXXX 1234" (bullets sometimes come out of the PDF as odd symbols)
CARD_MASK = re.compile(r"(?:(?:[^\w\s]|[xX]){2,}\s*\d{4}\b|final\s+\d{4})", re.IGNORECASE)

# Lines that are not spending: payments of the previous bill, balances, totals, limits.
SKIP = re.compile(
    r"pagamento|pgto|saldo anterior|saldo em atraso|total d|valor total|total a pagar|subtotal|limite|"
    r"credito de pagamento|pagto|resumo|vencimento|fechamento|saldo devedor|saldo restante|melhor dia",
    re.IGNORECASE,
)
# A section listing installments of FUTURE statements: ignore the rest of that page.
FUTURE = re.compile(r"pr[oó]xim[ao]s? faturas?|lan[cç]amentos futuros|parcelas a vencer|saldo parcelado|compras parceladas a vencer", re.IGNORECASE)
REFUND = re.compile(r"estorno|reembolso|devolu[cç][aã]o|cashback|cr[eé]dito", re.IGNORECASE)

DUE = re.compile(r"vencimento[^0-9]{0,40}(\d{1,2})[/.\-](\d{1,2})[/.\-](\d{2,4})", re.IGNORECASE)
DUE_NAMED = re.compile(rf"vencimento[^0-9]{{0,40}}(\d{{1,2}})\s*(?:de\s+)?({_MONTH_NAMES})[a-zç]*\.?\s*(?:de\s+)?(\d{{4}})", re.IGNORECASE)
TOTAL = re.compile(r"(?:total\s+(?:desta|da)\s+fatura|valor\s+total\s+da\s+fatura|total\s+a\s+pagar|valor\s+da\s+fatura)[^0-9\n]{0,40}?(\d{1,3}(?:\.\d{3})*,\d{2})", re.IGNORECASE)

ISSUERS = [("nubank", "Nubank"), ("nu pagamentos", "Nubank"), ("itau", "Itaú"), ("itaú", "Itaú"), ("bradesco", "Bradesco"),
           ("santander", "Santander"), ("banco inter", "Inter"), ("c6 bank", "C6 Bank"), ("caixa", "Caixa"),
           ("ourocard", "Banco do Brasil"), ("banco do brasil", "Banco do Brasil"), ("btg", "BTG"), ("xp ", "XP"),
           ("sicredi", "Sicredi"), ("sicoob", "Sicoob"), ("porto seguro", "Porto Seguro"), ("mercado pago", "Mercado Pago"),
           ("picpay", "PicPay"), ("neon", "Neon"), ("next", "Next"), ("will bank", "Will Bank"), ("pan", "Banco Pan")]


def _cents(text: str) -> int:
    return int(round(float(text.replace(".", "").replace(",", ".")) * 100))


def _year(y: str | None, fallback: int) -> int:
    if not y:
        return fallback
    y = int(y)
    return y + 2000 if y < 100 else y


def _safe_date(y: int, m: int, d: int) -> date | None:
    try:
        return date(y, m, d)
    except ValueError:
        return None


def _issuer(text: str) -> str | None:
    low = " " + re.sub(r"[^a-zà-ú0-9]+", " ", text.lower()) + " "
    for key, name in ISSUERS:
        if f" {key.strip()} " in low:
            return name
    return None


def _due_date(text: str) -> date | None:
    m = DUE.search(text)
    if m:
        return _safe_date(_year(m.group(3), date.today().year), int(m.group(2)), int(m.group(1)))
    m = DUE_NAMED.search(text)
    if m:
        return _safe_date(int(m.group(3)), MONTHS[m.group(2).lower()[:3]], int(m.group(1)))
    return None


def _pdf_text(upload: documents.Upload, password: str) -> list[str]:
    data, _pages = documents._read_pdf(upload, password)
    reader = PdfReader(io.BytesIO(data))
    pages = []
    for page in reader.pages:
        try:
            text = page.extract_text(extraction_mode="layout")
        except Exception:
            text = page.extract_text() or ""
        pages.append(text or "")
    return pages


_DATE_TOKEN = re.compile(r"^(\d{1,2})[/.\-](\d{1,2})(?:[/.\-](\d{2,4}))?$")
_GLUED_DATE = re.compile(rf"^(\d{{1,2}})({_MONTH_NAMES})[a-zç]*\.?$", re.IGNORECASE)  # "12SET"
_MONTH_TOKEN = re.compile(rf"^({_MONTH_NAMES})[a-zç]*\.?$", re.IGNORECASE)  # "SET", "set.", "setembro"
_AMOUNT_TOKEN = re.compile(r"^([-−–])?(?:R\$)?(\d{1,3}(?:\.\d{3})*,\d{2})([-−–]|[CD])?$", re.IGNORECASE)
_SIGN_TOKENS = {"-", "−", "–", "-r$", "−r$", "–r$"}
_FOREIGN = {"us$", "usd", "u$", "eur", "€", "eur$"}


def _date_at(tokens: list[str], i: int):
    """A date starting at tokens[i]: ((day, month, year text), tokens used) or (None, 0)."""
    tok = tokens[i]
    m = _DATE_TOKEN.match(tok)
    if m:
        return (int(m.group(1)), int(m.group(2)), m.group(3)), 1
    m = _GLUED_DATE.match(tok)
    if m:
        return (int(m.group(1)), MONTHS[m.group(2).lower()[:3]], None), 1
    if re.fullmatch(r"\d{1,2}", tok) and i + 1 < len(tokens):
        j = i + 1
        if tokens[j].lower() == "de" and j + 1 < len(tokens):
            j += 1
        mm = _MONTH_TOKEN.match(tokens[j])
        if mm:
            used = j - i + 1
            year = None
            k = j + 1
            if k < len(tokens) and tokens[k].lower() == "de" and k + 1 < len(tokens):
                k += 1
            if k < len(tokens) and re.fullmatch(r"\d{4}", tokens[k]):
                year, used = tokens[k], k - i + 1
            return (int(tok), MONTHS[mm.group(1).lower()[:3]], year), used
    return None, 0


def _records(line: str):
    """Splits one text line into transactions.

    A line may hold one transaction ("12/09 UBER *TRIP 23,40"), several side by side (statements
    printed in two columns), an installment column ("MAGALU 07/10 389,90") and both a R$ and a
    US$ amount. Yields dicts with day, month, year, words, installment and amounts (signed cents).
    """
    tokens = line.split()
    cur = None
    negative_next = False
    i = 0
    while i < len(tokens):
        tok = tokens[i]
        low = tok.lower()
        when, used = _date_at(tokens, i)
        if when and (cur is None or cur["amounts"]):
            if cur:
                yield cur
            cur = {"day": when[0], "month": when[1], "year": when[2], "words": [], "amounts": [], "installment": None}
            negative_next = False
            i += used
            continue
        if cur is None:
            i += 1
            continue
        if when and used == 1 and not cur["amounts"] and cur["words"] and when[2] is None:
            k, n = when[0], when[1]
            if 1 <= k <= n and 2 <= n <= 99 and not cur["installment"]:
                cur["installment"] = f"{k}/{n}"  # installment column ("03/10")
            cur["words"].append(tok)
            i += 1
            continue
        # A lone "-" is a minus sign only right before the amount ("- 59,90", "-R$ 59,90");
        # elsewhere it is part of the description ("Samsung - Parcela 4/10").
        if low in _SIGN_TOKENS and i + 1 < len(tokens) and _AMOUNT_TOKEN.match(tokens[i + 1]):
            negative_next = True
            i += 1
            continue
        m = _AMOUNT_TOKEN.match(tok)
        if m and cur["words"]:
            prev = tokens[i - 1].lower() if i else ""
            if prev in _FOREIGN and not cur["amounts"]:
                cur["words"].append(tok)  # "US$ 12,99" inside the description
            else:
                cents = _cents(m.group(2))
                if m.group(1) or negative_next or (m.group(3) or "").upper() in ("-", "−", "–", "C"):
                    cents = -cents
                cur["amounts"].append(cents)
                negative_next = False
            i += 1
            continue
        if low == "r$":
            i += 1
            continue
        if cur["amounts"]:
            if tok.upper() == "C" and i == len(tokens) - 1:
                cur["amounts"][-1] = -abs(cur["amounts"][-1])
            elif tok.upper() != "D":
                # Text after the amount that isn't a new date: the transaction ended.
                yield cur
                cur = None
            i += 1
            continue
        cur["words"].append(tok)
        i += 1
    if cur:
        yield cur


def _brl_first(text: str) -> bool | None:
    """Order of the R$ and US$ columns when the statement has both (from the header line)."""
    for line in text.splitlines():
        low = line.lower()
        if "r$" in low and "us$" in low and not re.search(r"\d,\d{2}", line):
            return low.index("r$") < low.index("us$")
    return None


def parse_statement_text(pages: list[str], today: date | None = None) -> dict:
    """Finds transactions in the text of a card statement (one string per page)."""
    today = today or date.today()
    full = "\n".join(pages)
    due = _due_date(full)
    ref = due or today
    total = TOTAL.search(full)
    brl_first = _brl_first(full)
    warnings = []
    transactions = []
    for page in pages:
        for raw in page.splitlines():
            line = raw.strip()
            if not line:
                continue
            if FUTURE.search(line):
                break  # the rest of this page lists future installments
            for rec in _records(line):
                if not rec["amounts"]:
                    continue
                desc = " ".join(rec["words"]).strip(" -–")
                if SKIP.search(desc) or len(re.sub(r"[^A-Za-zÀ-ú]", "", desc)) < 2:
                    continue
                day, month = rec["day"], rec["month"]
                if not 1 <= month <= 12:
                    continue
                # Statements print day/month only: purchases after the due month are from last year.
                year = _year(rec["year"], ref.year - (1 if month > ref.month else 0))
                tx_date = _safe_date(year, month, day)
                if not tx_date:
                    continue
                amounts = rec["amounts"]
                # With R$ and US$ columns, take the R$ one.
                cents = amounts[0] if len(amounts) > 1 and brl_first else amounts[-1]
                if REFUND.search(desc):
                    cents = -abs(cents)
                if not cents:
                    continue

                notes = []
                mask = CARD_MASK.search(desc)
                if mask:
                    notes.append(f"cartão {re.sub(r'[^0-9]', '', mask.group(0))[-4:]}")
                    desc = CARD_MASK.sub("", desc).strip()
                installment = rec["installment"]
                if not installment:
                    inst = INSTALLMENT.search(desc)
                    if inst and 1 <= int(inst.group(1)) <= int(inst.group(2)) and 2 <= int(inst.group(2)) <= 99:
                        installment = f"{int(inst.group(1))}/{int(inst.group(2))}"
                if installment:
                    k = int(installment.split("/")[0])
                    charged = due - timedelta(days=10) if due else None  # about the closing date
                    if k >= 2 and charged and tx_date < charged:
                        # Count it in the month it is charged, like the AI reader does.
                        notes.append(f"data da compra: {tx_date.isoformat()}")
                        tx_date = charged
                transactions.append(
                    {
                        "date": tx_date.isoformat(),
                        "description": desc[:300],
                        "merchant": clean_merchant(desc)[:200],
                        "amount_cents": cents,
                        "category": guess_category(desc),
                        "installment": installment,
                        "notes": " · ".join(notes),
                    }
                )

    if not transactions:
        if not full.strip():
            raise ExtractionError(
                "Este PDF não tem texto (parece uma imagem escaneada). Baixe a fatura em PDF pelo app ou site do banco, "
                "exporte em CSV/OFX, ou peça ao Claude (claude.ai) para transformar a fatura em CSV e importe o CSV."
            )
        raise ExtractionError(
            "Não encontrei lançamentos neste PDF. Se for uma fatura de cartão, me avise qual é o banco para ajustarmos o leitor; "
            "enquanto isso, tente exportar em CSV/OFX."
        )
    if not due:
        warnings.append("Não achei a data de vencimento; confira o ano das datas.")
    return {
        "document_type": "fatura_cartao",
        "issuer": _issuer(full),
        "reference_month": due.strftime("%Y-%m") if due else None,
        "due_date": due.isoformat() if due else None,
        "statement_total_cents": _cents(total.group(1)) if total else None,
        "transactions": transactions,
        "warnings": warnings,
    }


# ---------------------------------------------------------------- CSV / OFX


def _decode(data: bytes) -> str:
    for encoding in ("utf-8-sig", "cp1252", "latin-1"):
        try:
            return data.decode(encoding)
        except UnicodeDecodeError:
            continue
    return data.decode("latin-1", errors="replace")


def _parse_amount(text: str) -> int | None:
    s = re.sub(r"[R$\s]", "", text or "")
    if not s:
        return None
    neg = s.startswith(("-", "−")) or s.endswith("-")
    s = s.strip("-−+")
    if "," in s and "." in s:
        s = s.replace(".", "").replace(",", ".") if s.rfind(",") > s.rfind(".") else s.replace(",", "")
    elif "," in s:
        s = s.replace(",", ".")
    try:
        value = int(round(float(s) * 100))
    except ValueError:
        return None
    return -value if neg else value


def _parse_date(text: str) -> date | None:
    text = (text or "").strip()
    m = re.match(r"^(\d{4})-(\d{2})-(\d{2})", text)
    if m:
        return _safe_date(int(m.group(1)), int(m.group(2)), int(m.group(3)))
    m = re.match(r"^(\d{1,2})[/.\-](\d{1,2})[/.\-](\d{2,4})", text)
    if m:
        return _safe_date(_year(m.group(3), date.today().year), int(m.group(2)), int(m.group(1)))
    m = re.match(r"^(\d{4})(\d{2})(\d{2})", text)  # OFX: 20260912120000[-3:BRT]
    if m:
        return _safe_date(int(m.group(1)), int(m.group(2)), int(m.group(3)))
    return None


def _rows_to_result(rows: list[tuple[date, str, int]], issuer: str | None) -> dict:
    """rows: (date, description, signed amount as printed). Works out which sign means spending."""
    if not rows:
        raise ExtractionError("Não encontrei lançamentos neste arquivo.")
    negatives = sum(1 for _, _, a in rows if a < 0)
    # Bank account exports print spending as negative; card exports print it as positive.
    account_style = negatives > len(rows) / 2
    transactions = []
    skipped_income = 0
    for d, desc, amount in rows:
        if SKIP.search(desc):
            continue
        cents = -amount if account_style else amount
        if account_style and cents < 0:
            skipped_income += 1  # money coming in: not a spending
            continue
        if not cents:
            continue
        installment = None
        inst = INSTALLMENT.search(desc)
        if inst and 1 <= int(inst.group(1)) <= int(inst.group(2)) and 2 <= int(inst.group(2)) <= 48:
            installment = f"{int(inst.group(1))}/{int(inst.group(2))}"
        transactions.append(
            {
                "date": d.isoformat(),
                "description": desc[:300],
                "merchant": clean_merchant(desc)[:200],
                "amount_cents": cents,
                "category": guess_category(desc),
                "installment": installment,
                "notes": "",
            }
        )
    warnings = []
    if skipped_income:
        warnings.append(f"{skipped_income} entrada(s) de dinheiro (salário, Pix recebido…) foram ignoradas: o app registra só gastos.")
    if not transactions:
        raise ExtractionError("O arquivo não tem gastos (só pagamentos ou entradas de dinheiro).")
    months = sorted(t["date"][:7] for t in transactions)
    return {
        "document_type": "outro",
        "issuer": issuer,
        "reference_month": months[-1],
        "due_date": None,
        "statement_total_cents": None,
        "transactions": transactions,
        "warnings": warnings,
    }


DATE_COLS = ("data", "date", "data lancamento", "data lançamento", "data da compra", "dt")
DESC_COLS = ("descricao", "descrição", "title", "titulo", "título", "historico", "histórico", "lancamento", "lançamento",
             "estabelecimento", "description", "memo", "detalhes")
AMOUNT_COLS = ("valor", "amount", "valor (r$)", "valor r$", "valor em r$", "value", "quantia")


def parse_csv(data: bytes, filename: str = "") -> dict:
    text = _decode(data)
    sample = text[:4096]
    try:
        dialect = csv.Sniffer().sniff(sample, delimiters=",;\t")
    except csv.Error:
        dialect = csv.excel
        dialect.delimiter = ";" if sample.count(";") > sample.count(",") else ","
    reader = list(csv.reader(io.StringIO(text), dialect))
    header_idx, cols = None, None
    for i, row in enumerate(reader[:15]):
        names = [c.strip().lower() for c in row]
        find = lambda options: next((j for j, n in enumerate(names) if n in options), None)  # noqa: E731
        d, s, a = find(DATE_COLS), find(DESC_COLS), find(AMOUNT_COLS)
        if d is not None and s is not None and a is not None:
            header_idx, cols = i, (d, s, a)
            break
    if cols is None:
        raise ExtractionError(
            "Não reconheci as colunas do CSV. Ele precisa ter colunas de data, descrição e valor "
            "(por exemplo: data;descricao;valor)."
        )
    rows = []
    for row in reader[header_idx + 1:]:
        if len(row) <= max(cols):
            continue
        d, amount = _parse_date(row[cols[0]]), _parse_amount(row[cols[2]])
        desc = re.sub(r"\s+", " ", row[cols[1]]).strip()
        if d and amount is not None and desc:
            rows.append((d, desc, amount))
    return _rows_to_result(rows, _issuer(filename + " " + text[:2000]))


def parse_ofx(data: bytes, filename: str = "") -> dict:
    text = _decode(data)
    rows = []
    for block in re.findall(r"<STMTTRN>(.*?)(?:</STMTTRN>|(?=<STMTTRN>)|</BANKTRANLIST>)", text, re.IGNORECASE | re.DOTALL):
        def tag(name):
            m = re.search(rf"<{name}>([^<\r\n]*)", block, re.IGNORECASE)
            return m.group(1).strip() if m else ""

        d, amount = _parse_date(tag("DTPOSTED")), _parse_amount(tag("TRNAMT").replace(",", "."))
        desc = tag("MEMO") or tag("NAME")
        if d and amount is not None and desc:
            rows.append((d, re.sub(r"\s+", " ", desc), amount))
    if not rows:
        raise ExtractionError("Não encontrei lançamentos neste arquivo OFX.")
    org = re.search(r"<ORG>([^<\r\n]+)", text, re.IGNORECASE)
    return _rows_to_result(rows, _issuer((org.group(1) if org else "") + " " + filename))


# ---------------------------------------------------------------- entry point


def kind(upload: documents.Upload) -> str:
    name = upload.filename.lower()
    head = upload.data[:200].lstrip().upper()
    if upload.data[:5] == b"%PDF-" or name.endswith(".pdf"):
        return "pdf"
    if name.endswith((".ofx", ".qfx")) or head.startswith(b"OFXHEADER") or b"<OFX>" in upload.data[:2000].upper():
        return "ofx"
    if name.endswith((".csv", ".txt")):
        return "csv"
    return "image"


def read(uploads: list[documents.Upload], password: str = "") -> dict:
    kinds = {kind(u) for u in uploads}
    if "image" in kinds:
        raise ExtractionError(
            "Fotos precisam da leitura com IA (paga). De graça, envie o PDF da fatura baixado do app/site do banco, "
            "ou o arquivo CSV/OFX. Outra opção: mande a foto no claude.ai pedindo uma tabela CSV e importe o CSV."
        )
    if len(kinds) > 1:
        raise ExtractionError("Envie um tipo de arquivo por vez (só PDFs, só um CSV ou só um OFX).")
    if kinds == {"pdf"}:
        pages = []
        for u in uploads:
            pages.extend(_pdf_text(u, password))
        result = parse_statement_text(pages)
    else:
        parts = [(parse_csv if kinds == {"csv"} else parse_ofx)(u.data, u.filename) for u in uploads]
        result = parts[0]
        for extra in parts[1:]:
            result["transactions"] += extra["transactions"]
            result["warnings"] += extra["warnings"]
    result.update(model="local", input_tokens=None, output_tokens=None)
    return result
