"""Free statement reader: no AI, no internet.

- PDF statements generated by the bank carry real text: each line that starts with a date
  and ends with an amount is a transaction.
- CSV and OFX exports are read column by column.

Returns the same shape as extractor.extract(), so the review screen works the same way.
"""

import csv
import io
import re
from datetime import date, timedelta

from pypdf import PdfReader

from . import documents
from .categorizer import clean_merchant, guess_category
from .extractor import ExtractionError

MONTHS = {"jan": 1, "fev": 2, "feb": 2, "mar": 3, "abr": 4, "apr": 4, "mai": 5, "may": 5, "jun": 6, "jul": 7,
          "ago": 8, "aug": 8, "set": 9, "sep": 9, "out": 10, "oct": 10, "nov": 11, "dez": 12, "dec": 12}
_MONTH_NAMES = "|".join(MONTHS)

# "12/09", "12/09/2026", "12.09.26"
_NUMERIC_DATE = r"(?P<d>\d{1,2})[/.\-](?P<m>\d{1,2})(?:[/.\-](?P<y>\d{2,4}))?"
# "12 SET", "12 de set. 2026", "12set"
_NAMED_DATE = rf"(?P<d2>\d{{1,2}})\s*(?:de\s+)?(?P<mn>{_MONTH_NAMES})[a-zç]*\.?(?:\s*(?:de\s+)?(?P<y2>\d{{4}}))?"
_AMOUNT = r"(?P<neg>[-−–])?\s*(?:R\$\s*)?(?P<amount>\d{1,3}(?:\.\d{3})*,\d{2})(?P<trail>\s*[-−–]|\s*[CD]\b)?"

LINE = re.compile(rf"^\s*(?:{_NUMERIC_DATE}|{_NAMED_DATE})\s+(?P<desc>.+?)\s+{_AMOUNT}\s*$", re.IGNORECASE)
INSTALLMENT = re.compile(r"(?:parc(?:ela)?\.?\s*)?\b(\d{1,2})\s*(?:/|de)\s*(\d{1,2})\b(?!.*\b\d{1,2}\s*(?:/|de)\s*\d{1,2}\b)", re.IGNORECASE)
# "•••• 1234", "**** 1234", "XXXX 1234" (bullets sometimes come out of the PDF as odd symbols)
CARD_MASK = re.compile(r"(?:(?:[^\w\s]|[xX]){2,}\s*\d{4}\b|final\s+\d{4})", re.IGNORECASE)

# Lines that are not spending: payments of the previous bill, balances, totals, limits.
SKIP = re.compile(
    r"pagamento|pgto|saldo anterior|saldo em atraso|total d|valor total|total a pagar|subtotal|limite|"
    r"credito de pagamento|pagto|resumo|vencimento|fechamento|saldo devedor|saldo restante|melhor dia",
    re.IGNORECASE,
)
# A section listing installments of FUTURE statements: ignore the rest of that page.
FUTURE = re.compile(r"pr[oó]xim[ao]s? faturas?|lan[cç]amentos futuros|parcelas a vencer|saldo parcelado|compras parceladas a vencer", re.IGNORECASE)
REFUND = re.compile(r"estorno|reembolso|devolu[cç][aã]o|cashback|cr[eé]dito", re.IGNORECASE)

DUE = re.compile(r"vencimento[^0-9]{0,40}(\d{1,2})[/.\-](\d{1,2})[/.\-](\d{2,4})", re.IGNORECASE)
DUE_NAMED = re.compile(rf"vencimento[^0-9]{{0,40}}(\d{{1,2}})\s*(?:de\s+)?({_MONTH_NAMES})[a-zç]*\.?\s*(?:de\s+)?(\d{{4}})", re.IGNORECASE)
TOTAL = re.compile(r"(?:total\s+(?:desta|da)\s+fatura|valor\s+total\s+da\s+fatura|total\s+a\s+pagar|valor\s+da\s+fatura)[^0-9\n]{0,40}?(\d{1,3}(?:\.\d{3})*,\d{2})", re.IGNORECASE)

ISSUERS = [("nubank", "Nubank"), ("nu pagamentos", "Nubank"), ("itau", "Itaú"), ("itaú", "Itaú"), ("bradesco", "Bradesco"),
           ("santander", "Santander"), ("banco inter", "Inter"), ("c6 bank", "C6 Bank"), ("caixa", "Caixa"),
           ("ourocard", "Banco do Brasil"), ("banco do brasil", "Banco do Brasil"), ("btg", "BTG"), ("xp ", "XP"),
           ("sicredi", "Sicredi"), ("sicoob", "Sicoob"), ("porto seguro", "Porto Seguro"), ("mercado pago", "Mercado Pago"),
           ("picpay", "PicPay"), ("neon", "Neon"), ("next", "Next"), ("will bank", "Will Bank"), ("pan", "Banco Pan")]


def _cents(text: str) -> int:
    return int(round(float(text.replace(".", "").replace(",", ".")) * 100))


def _year(y: str | None, fallback: int) -> int:
    if not y:
        return fallback
    y = int(y)
    return y + 2000 if y < 100 else y


def _safe_date(y: int, m: int, d: int) -> date | None:
    try:
        return date(y, m, d)
    except ValueError:
        return None


def _issuer(text: str) -> str | None:
    low = " " + re.sub(r"[^a-zà-ú0-9]+", " ", text.lower()) + " "
    for key, name in ISSUERS:
        if f" {key.strip()} " in low:
            return name
    return None


def _due_date(text: str) -> date | None:
    m = DUE.search(text)
    if m:
        return _safe_date(_year(m.group(3), date.today().year), int(m.group(2)), int(m.group(1)))
    m = DUE_NAMED.search(text)
    if m:
        return _safe_date(int(m.group(3)), MONTHS[m.group(2).lower()[:3]], int(m.group(1)))
    return None


def _pdf_text(upload: documents.Upload, password: str) -> list[str]:
    data, _pages = documents._read_pdf(upload, password)
    reader = PdfReader(io.BytesIO(data))
    pages = []
    for page in reader.pages:
        try:
            text = page.extract_text(extraction_mode="layout")
        except Exception:
            text = page.extract_text() or ""
        pages.append(text or "")
    return pages


def parse_statement_text(pages: list[str], today: date | None = None) -> dict:
    """Finds transactions in the text of a card statement (one string per page)."""
    today = today or date.today()
    full = "\n".join(pages)
    due = _due_date(full)
    ref = due or today
    total = TOTAL.search(full)
    warnings = []
    transactions = []
    for page in pages:
        for raw in page.splitlines():
            line = raw.strip()
            if not line:
                continue
            if FUTURE.search(line):
                break  # the rest of this page lists future installments
            m = LINE.match(line)
            if not m:
                continue
            desc = re.sub(r"\s{2,}", " ", m.group("desc")).strip(" -–")
            if SKIP.search(desc) or len(desc) < 2:
                continue
            if m.group("d"):
                day, month = int(m.group("d")), int(m.group("m"))
                year_txt = m.group("y")
            else:
                day, month = int(m.group("d2")), MONTHS[m.group("mn").lower()[:3]]
                year_txt = m.group("y2")
            if not 1 <= month <= 12:
                continue
            # Statements print day/month only: purchases after the due month are from last year.
            year = _year(year_txt, ref.year - (1 if month > ref.month else 0))
            tx_date = _safe_date(year, month, day)
            if not tx_date:
                continue

            cents = _cents(m.group("amount"))
            trail = (m.group("trail") or "").strip().upper()
            if m.group("neg") or trail in ("-", "−", "–", "C") or REFUND.search(desc):
                cents = -cents
            if not cents:
                continue

            notes = []
            mask = CARD_MASK.search(desc)
            if mask:
                notes.append(f"cartão {re.sub(r'[^0-9]', '', mask.group(0))[-4:]}")
                desc = CARD_MASK.sub("", desc).strip()
            installment = None
            inst = INSTALLMENT.search(desc)
            if inst:
                k, n = int(inst.group(1)), int(inst.group(2))
                if 1 <= k <= n and 2 <= n <= 48:
                    installment = f"{k}/{n}"
                    charged = due - timedelta(days=10) if due else None  # about the closing date
                    if k >= 2 and charged and tx_date < charged:
                        # Count it in the month it is charged, like the AI reader does.
                        notes.append(f"data da compra: {tx_date.isoformat()}")
                        tx_date = charged
            transactions.append(
                {
                    "date": tx_date.isoformat(),
                    "description": desc[:300],
                    "merchant": clean_merchant(desc)[:200],
                    "amount_cents": cents,
                    "category": guess_category(desc),
                    "installment": installment,
                    "notes": " · ".join(notes),
                }
            )

    if not transactions:
        if not full.strip():
            raise ExtractionError(
                "Este PDF não tem texto (parece uma imagem escaneada). Baixe a fatura em PDF pelo app ou site do banco, "
                "exporte em CSV/OFX, ou peça ao Claude (claude.ai) para transformar a fatura em CSV e importe o CSV."
            )
        raise ExtractionError(
            "Não encontrei lançamentos neste PDF. Se for uma fatura de cartão, me avise qual é o banco para ajustarmos o leitor; "
            "enquanto isso, tente exportar em CSV/OFX."
        )
    if not due:
        warnings.append("Não achei a data de vencimento; confira o ano das datas.")
    return {
        "document_type": "fatura_cartao",
        "issuer": _issuer(full),
        "reference_month": due.strftime("%Y-%m") if due else None,
        "due_date": due.isoformat() if due else None,
        "statement_total_cents": _cents(total.group(1)) if total else None,
        "transactions": transactions,
        "warnings": warnings,
    }


# ---------------------------------------------------------------- CSV / OFX


def _decode(data: bytes) -> str:
    for encoding in ("utf-8-sig", "cp1252", "latin-1"):
        try:
            return data.decode(encoding)
        except UnicodeDecodeError:
            continue
    return data.decode("latin-1", errors="replace")


def _parse_amount(text: str) -> int | None:
    s = re.sub(r"[R$\s]", "", text or "")
    if not s:
        return None
    neg = s.startswith(("-", "−")) or s.endswith("-")
    s = s.strip("-−+")
    if "," in s and "." in s:
        s = s.replace(".", "").replace(",", ".") if s.rfind(",") > s.rfind(".") else s.replace(",", "")
    elif "," in s:
        s = s.replace(",", ".")
    try:
        value = int(round(float(s) * 100))
    except ValueError:
        return None
    return -value if neg else value


def _parse_date(text: str) -> date | None:
    text = (text or "").strip()
    m = re.match(r"^(\d{4})-(\d{2})-(\d{2})", text)
    if m:
        return _safe_date(int(m.group(1)), int(m.group(2)), int(m.group(3)))
    m = re.match(r"^(\d{1,2})[/.\-](\d{1,2})[/.\-](\d{2,4})", text)
    if m:
        return _safe_date(_year(m.group(3), date.today().year), int(m.group(2)), int(m.group(1)))
    m = re.match(r"^(\d{4})(\d{2})(\d{2})", text)  # OFX: 20260912120000[-3:BRT]
    if m:
        return _safe_date(int(m.group(1)), int(m.group(2)), int(m.group(3)))
    return None


def _rows_to_result(rows: list[tuple[date, str, int]], issuer: str | None) -> dict:
    """rows: (date, description, signed amount as printed). Works out which sign means spending."""
    if not rows:
        raise ExtractionError("Não encontrei lançamentos neste arquivo.")
    negatives = sum(1 for _, _, a in rows if a < 0)
    # Bank account exports print spending as negative; card exports print it as positive.
    account_style = negatives > len(rows) / 2
    transactions = []
    skipped_income = 0
    for d, desc, amount in rows:
        if SKIP.search(desc):
            continue
        cents = -amount if account_style else amount
        if account_style and cents < 0:
            skipped_income += 1  # money coming in: not a spending
            continue
        if not cents:
            continue
        installment = None
        inst = INSTALLMENT.search(desc)
        if inst and 1 <= int(inst.group(1)) <= int(inst.group(2)) and 2 <= int(inst.group(2)) <= 48:
            installment = f"{int(inst.group(1))}/{int(inst.group(2))}"
        transactions.append(
            {
                "date": d.isoformat(),
                "description": desc[:300],
                "merchant": clean_merchant(desc)[:200],
                "amount_cents": cents,
                "category": guess_category(desc),
                "installment": installment,
                "notes": "",
            }
        )
    warnings = []
    if skipped_income:
        warnings.append(f"{skipped_income} entrada(s) de dinheiro (salário, Pix recebido…) foram ignoradas: o app registra só gastos.")
    if not transactions:
        raise ExtractionError("O arquivo não tem gastos (só pagamentos ou entradas de dinheiro).")
    months = sorted(t["date"][:7] for t in transactions)
    return {
        "document_type": "outro",
        "issuer": issuer,
        "reference_month": months[-1],
        "due_date": None,
        "statement_total_cents": None,
        "transactions": transactions,
        "warnings": warnings,
    }


DATE_COLS = ("data", "date", "data lancamento", "data lançamento", "data da compra", "dt")
DESC_COLS = ("descricao", "descrição", "title", "titulo", "título", "historico", "histórico", "lancamento", "lançamento",
             "estabelecimento", "description", "memo", "detalhes")
AMOUNT_COLS = ("valor", "amount", "valor (r$)", "valor r$", "valor em r$", "value", "quantia")


def parse_csv(data: bytes, filename: str = "") -> dict:
    text = _decode(data)
    sample = text[:4096]
    try:
        dialect = csv.Sniffer().sniff(sample, delimiters=",;\t")
    except csv.Error:
        dialect = csv.excel
        dialect.delimiter = ";" if sample.count(";") > sample.count(",") else ","
    reader = list(csv.reader(io.StringIO(text), dialect))
    header_idx, cols = None, None
    for i, row in enumerate(reader[:15]):
        names = [c.strip().lower() for c in row]
        find = lambda options: next((j for j, n in enumerate(names) if n in options), None)  # noqa: E731
        d, s, a = find(DATE_COLS), find(DESC_COLS), find(AMOUNT_COLS)
        if d is not None and s is not None and a is not None:
            header_idx, cols = i, (d, s, a)
            break
    if cols is None:
        raise ExtractionError(
            "Não reconheci as colunas do CSV. Ele precisa ter colunas de data, descrição e valor "
            "(por exemplo: data;descricao;valor)."
        )
    rows = []
    for row in reader[header_idx + 1:]:
        if len(row) <= max(cols):
            continue
        d, amount = _parse_date(row[cols[0]]), _parse_amount(row[cols[2]])
        desc = re.sub(r"\s+", " ", row[cols[1]]).strip()
        if d and amount is not None and desc:
            rows.append((d, desc, amount))
    return _rows_to_result(rows, _issuer(filename + " " + text[:2000]))


def parse_ofx(data: bytes, filename: str = "") -> dict:
    text = _decode(data)
    rows = []
    for block in re.findall(r"<STMTTRN>(.*?)(?:</STMTTRN>|(?=<STMTTRN>)|</BANKTRANLIST>)", text, re.IGNORECASE | re.DOTALL):
        def tag(name):
            m = re.search(rf"<{name}>([^<\r\n]*)", block, re.IGNORECASE)
            return m.group(1).strip() if m else ""

        d, amount = _parse_date(tag("DTPOSTED")), _parse_amount(tag("TRNAMT").replace(",", "."))
        desc = tag("MEMO") or tag("NAME")
        if d and amount is not None and desc:
            rows.append((d, re.sub(r"\s+", " ", desc), amount))
    if not rows:
        raise ExtractionError("Não encontrei lançamentos neste arquivo OFX.")
    org = re.search(r"<ORG>([^<\r\n]+)", text, re.IGNORECASE)
    return _rows_to_result(rows, _issuer((org.group(1) if org else "") + " " + filename))


# ---------------------------------------------------------------- entry point


def kind(upload: documents.Upload) -> str:
    name = upload.filename.lower()
    head = upload.data[:200].lstrip().upper()
    if upload.data[:5] == b"%PDF-" or name.endswith(".pdf"):
        return "pdf"
    if name.endswith((".ofx", ".qfx")) or head.startswith(b"OFXHEADER") or b"<OFX>" in upload.data[:2000].upper():
        return "ofx"
    if name.endswith((".csv", ".txt")):
        return "csv"
    return "image"


def read(uploads: list[documents.Upload], password: str = "") -> dict:
    kinds = {kind(u) for u in uploads}
    if "image" in kinds:
        raise ExtractionError(
            "Fotos precisam da leitura com IA (paga). De graça, envie o PDF da fatura baixado do app/site do banco, "
            "ou o arquivo CSV/OFX. Outra opção: mande a foto no claude.ai pedindo uma tabela CSV e importe o CSV."
        )
    if len(kinds) > 1:
        raise ExtractionError("Envie um tipo de arquivo por vez (só PDFs, só um CSV ou só um OFX).")
    if kinds == {"pdf"}:
        pages = []
        for u in uploads:
            pages.extend(_pdf_text(u, password))
        result = parse_statement_text(pages)
    else:
        parts = [(parse_csv if kinds == {"csv"} else parse_ofx)(u.data, u.filename) for u in uploads]
        result = parts[0]
        for extra in parts[1:]:
            result["transactions"] += extra["transactions"]
            result["warnings"] += extra["warnings"]
    result.update(model="local", input_tokens=None, output_tokens=None)
    return result
